# Generated by Django 5.1 on 2024-08-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "db_table": "task_manager_category",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"], "verbose_name": "Task"},
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время начала выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(verbose_name="Срок выполнения"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(verbose_name="Описание задачи"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("N", "New"),
                    ("I", "In Progress"),
                    ("P", "Pending"),
                    ("B", "Blocked"),
                    ("D", "Done"),
                ],
                max_length=50,
                verbose_name="Тип задачи",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Наименование задачи"
            ),
        ),
        migrations.AlterModelTable(
            name="task",
            table="task_manager_task",
        ),
        migrations.AddField(
            model_name="task",
            name="categories",
            field=models.ManyToManyField(to="tasks.category"),
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование подзадачи",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание подзадачи")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "New"),
                            ("I", "In Progress"),
                            ("P", "Pending"),
                            ("B", "Blocked"),
                            ("D", "Done"),
                        ],
                        max_length=50,
                        verbose_name="Тип подзадачи",
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="Срок выполнения")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время начала выполнения"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                        verbose_name="Основная задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subtask",
                "db_table": "task_manager_subtask",
                "ordering": ["-created_at"],
            },
        ),
    ]
