# Generated by Django 5.1 on 2024-08-30 17:29

import django.db.models.deletion
import tasks.variables
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_category_alter_task_options_alter_task_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subtask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Subtask",
                "verbose_name_plural": "Subtasks",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=tasks.variables.Task_name.task_choices,
                default=tasks.variables.Task_name["NEW"],
                max_length=15,
                verbose_name="Тип подзадачи",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=tasks.variables.Task_name.task_choices,
                default=tasks.variables.Task_name["NEW"],
                max_length=15,
                verbose_name="Тип задачи",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_subtask"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(fields=("title",), name="unique_task"),
        ),
    ]
